### ISSUE TITLE
Release 0.99?

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#101]
It is has been a while since the last release. Since then the FreeBSD port is living off seperate commits rather than a real tag. Can you make that happen?

**Comment by johnmehr** [comment]
I was hoping to get some feedback from Graham about Issue #98 before tagging the next release (plus I really should get Issue #92 resolved -- hopefully this weekend).  Maybe wait a week?

**Comment by johnmehr** [comment]
Done!
