### ISSUE TITLE
gitup not sending SNI and blocked by some server

### ISSUE THREAD

**Issue by Alex6357** [johnmehr/gitup#104]
ustclug/discussions#464

Adding server_name (SNI) into TLS Client Hello may solve this issue.

**Comment by Alex6357** [comment]
Another one opened a pr #103.

**Comment by johnmehr** [comment]
Thank you for the patch!  I just merged it.  How are things working for you now?

**Comment by johnmehr** [comment]
Please let me know if there are any further issues.  Thank you!
