### ISSUE TITLE
gitup: find_local_tree: /usr/src/contrib/bc/locales/de_AT.ISO8859-1.msg: No such file or directory

### ISSUE THREAD

**Issue by CyberCr33p** [johnmehr/gitup#12]
I install gitup and tried it with the default config.

The first time I run:

`gitup stable`

everything is fine.

If I run the above command for second time then I get this:

gitup: find_local_tree: /usr/src/contrib/bc/locales/de_AT.ISO8859-1.msg: No such file or directory

`ls -la /usr/src/contrib/bc/locales/de_AT.ISO8859-1.msg`
lrwxr-xr-x  1 root  wheel  20 Dec 25 13:02 /usr/src/contrib/bc/locales/de_AT.ISO8859-1.msg -> de_DE.ISO8859-1.msg?

The correct filename is:

/usr/src/contrib/bc/locales/de_DE.ISO8859-1.msg (it doesn't have a questionmark at the end)

**Comment by johnmehr** [comment]
I think this is fixed now.  Could you please give it another try and let me know how it goes?

**Comment by CyberCr33p** [comment]
Yes everything is ok now.

**Comment by johnmehr** [comment]
Thank you!
