### ISSUE TITLE
Question about releng/12.2

### ISSUE THREAD

**Issue by CyberCr33p** [johnmehr/gitup#13]
Github doesn't have releng/12.2

Is it possible to use git.freebsd.org ?

**Comment by johnmehr** [comment]
It looks like there's an issue with "incompatible hashes" that's interfering with the mirroring of the releng branches.  There was an email posted to git@ the other day where they indicated "Ideally, we can push this final commit to master before New Years and then we can start mirroring the new main/stable/releng into GH." so it looks like the releng branches should be back on github.com in a couple of days.

**Comment by CyberCr33p** [comment]
Thank you for the reply and your work with gitup.
