### ISSUE TITLE
Confusing: options come before section

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#16]
```
Usage: gitup <section> [-ckrV] [-h checksum] [-t tag] [-u pack file] [-v verbosity] [-w checksum]
```
Is it intentional that the options come *after*  the section? It is confusing compared to other CLI tools. I don't see how the options are specific to a section.

**Comment by johnmehr** [comment]
I just relaxed the requirement that the section must be the first command line parameter -- it can now appear anywhere in the list of arguments.  Thank you!

**Comment by michael-o** [comment]
Works for me now.
