### ISSUE TITLE
Write .gituprevision in the root of the clone

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#19]
Since I moved from Subversion to gitup I do not see revision in `uname -a` anymore. This is especially problematic for users which have to report issues and requested the used commit id. I know that this is not really related to gitup, but here is my proposal:

When a clone or a pull happens to a section create/update a `.gituprevision` file in that same target directory ideally to the same format the official Git client would procude. In the next step `sys/conf/newvers.sh` can be modified to readin that file and make `uname -a` just like using Subversion or Git.

Git code: https://github.com/freebsd/freebsd-src/blob/098dbd7ff7f3da9dda03802cdb2d8755f816eada/sys/conf/newvers.sh#L249-L264

**Comment by johnmehr** [comment]
Hello,

I just pushed out an update to create a .gituprevision file in the target path which stores the branch, a '-' and the first nine digits of the want commit.  How does it look?

**Comment by michael-o** [comment]
Thank you for the quick turnaround, looking into. A hyphen might be problematic because a vendor branch can contain a hyphen. When `newvers.sh` should perform a `cut` it should expect maybe just two columns instead of 2+.

**Comment by michael-o** [comment]
Tested. Works for me. I would highly prefer something which is not allowed in a [branch name](https://stackoverflow.com/a/3651867/696632). Colon seems good to me.

**Comment by johnmehr** [comment]
I just changed the separator to a colon and pushed the changes.

**Comment by michael-o** [comment]
Works for me!

**Comment by emaste** [comment]
> sys/conf/newvers.sh can be modified
Will you submit a patch for that as well?

**Comment by michael-o** [comment]
> 
> 
> > sys/conf/newvers.sh can be modified
> > Will you submit a patch for that as well?

If you'd review, I'd be happy to next week.

**Comment by emaste** [comment]
Sounds good, tag me on the review and I'll look.

**Comment by michael-o** [comment]
Here you go folks: https://github.com/freebsd/freebsd-src/pull/449
