### ISSUE TITLE
Weird output in edge case

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#20]
Consider the following:
```
# /gitup stable
# Host: github.com
# Port: 443
# Repository: /freebsd/freebsd
# Target: /usr/src
# Have: 41cf333f9b2a494e7bb54f42a3790b6df99d09c9
# Want: 41cf333f9b2a494e7bb54f42a3790b6df99d09c9
# Branch: refs/heads/stable/12
```
So far so good. Now I accidentially tried a commit from main:
```
# /gitup stable -w fb6bc290fb342864f5362ab9cef7dd214df05cf3
# Host: github.com
# Port: 443
# Repository: /freebsd/freebsd
# Target: /usr/src
# Have: 41cf333f9b2a494e7bb54f42a3790b6df99d09c9
# Want: fb6bc290fb342864f5362ab9cef7dd214df05cf3
# Want: fb6bc290fb342864f5362ab9cef7dd214df05cf3
# Branch:/usr/src/# Action: pull
```

The output is weird. The original Git client shows:
```
root@bsd1srv:~/gitup ((686e41a...) %)
```

I don't know how far this can be handled, but showing `(detached)` as branch would be more than helpful.

**Comment by johnmehr** [comment]
I fixed the bug in the display (thank you!) but it doesn't look like there's a currently a solution to warning someone when a want ends up switching branches.  Because gitup only deals with shallow clones, the full commit history is not available.  I did some research and it doesn't look like there's a way to query the server for this information -- I was not able to find a way to request just the commit history of a branch.  If git ever implements this feature, I definitely want to add it and I'll be keeping an eye on future releases to see if it ever does.

**Comment by michael-o** [comment]
I will try this out, but I think there is room for improvement:
* `\n` is missing from the `printf`. Am I wrong?
* Maybe a `(detached)` would be better than nothing from a user's PoV?
* The `.gituprevision` continues to contain the previous branch even if `-w` has been passed. This looks wrong to me.

**Comment by michael-o** [comment]
If there is no way to detect that this commit belongs to a previous point in time of a branch, I am fine with that. With shall clones, impossible. Git itself does `git branch --contains $COMMIT_ID` but you need a full clone. Just the comments and that's it.

**Comment by johnmehr** [comment]
Since there's no way to currently find out which branch a given commit id lives in, do you think it would be best to use (detached) in .gituprevision, either replacing it or augmenting it (maybe something like "release/11.4 detached")?

**Comment by michael-o** [comment]
I think augmentation will be wrong because you cannot assume that the detached commit lives in the same branch as the one configured in `gitup.conf`. I would not rely on that. I as have shown in the example my branch is `stable/12`, but I wanted `fb6bc290fb342864f5362ab9cef7dd214df05cf3` from main.
In short: I would use `(detached)` and don't make any further asssumptions. In `.gituprevision` one has to replace the real branch with `(detached)` when the branch cannot be determined reliably: `(detached):fb6bc290f`.

**Comment by johnmehr** [comment]
How does it look now?

**Comment by michael-o** [comment]
Looks very good now. I see more room for improvement, but in totally unrelated code spots. I am fine in closing.
