### ISSUE TITLE
gitup violates RFC 7230 in several aspects

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#21]
I have noticed that gitup violates RFC 7230 and is not a compliant HTTP client. Strict servers will reject, some maybe more permissive.

Issues I have noticed so far:
* Incorrect line separator for request line and headers: It is imperative is to use `\r\n` because this is the LS for HTTP. I know that the command is printed with `fprintf(stderr, ...)` and will lead to trouble. One solution here would be to replace the two chars for verbose printing purposes with four chars: `\\r\\n`.
* Host header is in some cases incomplete: RFC says that the port is optional if and only if it is the default port for a scheme. Consider a server is serving `repo.example.com:443` and `repo.example.com:8443`. Since you omit the port altogether and the default virtual host is on `443` all requests will be routed there and may return a `404`.
* Parsing of the status line is incorrect: The reason phrase is defined as optional and deprecated. A server may omit it. You have to test for `HTTP/1.1 `. To process further one needs to read to the first `\r\n`. In fact, the status line could be anything. Even: `HTTP/1.1. Alright!\r\n`

If you need exact references, let me know.

Disclaimer: I am a curl, Apache Tomcat and Apache HttpComponents committer.

**Comment by johnmehr** [comment]
I think I've fixed all three items.  How does it look now?

**Comment by michael-o** [comment]
Going through...

**Comment by michael-o** [comment]
* Line separators are fine now
* The status handling looks a bit awkward. The simplest way is to do:
```
	if ((status_start = strstr(connection->response, "HTTP/1.1 200 ")) != connection->response)
		errc(EXIT_FAILURE, EINVAL, "process_command: read failure:\n%s\n", connection->response);
```
The extended one to add another verification that `\r\n\` after these 13 chars is present. That's it.

If you want to keep the current code, you can do the following:
```
	if ((status_start = strstr(connection->response, "HTTP/1.1 ")) != connection->response)
		errc(EXIT_FAILURE, EINVAL, "process_command: read failure:\n%s\n", connection->response);

	status_end    = strstr(connection->response + 10, "\r\n");
	status_length = status_end - status_start - 10;
	memcpy(status, status_start + 10, 4);

	if (strncmp(status, "200 ", 4) != 0)
```
Explanation: The status line is `HTTP-version SP status-code SP reason-phrase CRLF`. `HTTP-version SP` is handled, `status-code` is always 3 digit + the obligatory space. The rest is optional. Line separator is handled. So you could trim down status to 4 chars when you don't need `\0`.

**Comment by johnmehr** [comment]
I've reverted back to using the (updated) cleaner code.  Thank you!

**Comment by michael-o** [comment]
Looks good for me!
