### ISSUE TITLE
Socket to remote server never explicitly closed

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#22]
Please call me stupid, but I fail to see where the TCP socket is closed. `main()` has
https://github.com/johnmehr/gitup/blob/4463ee04e02298f99b83b086c858f1b3293861bd/gitup.c#L2340-L2344
but I fail to see a `close(connection.socket_descriptor)`.  `SSL_shutdown()` only terminates the TLS session with a `close_notify`, but does not close the underlying socket. This may lead to a broken socket on the peer's side.

I'd be happy to be proved wrong.

**Comment by johnmehr** [comment]
Done.  Thank you!

**Comment by michael-o** [comment]
Thanks, but shouldn't the socket be closed *after* the TLS context has been shutdown? From a server's PoV this will look like an unclean TLS shutdown.

**Comment by johnmehr** [comment]
Whoops.  Sorry about that!

**Comment by michael-o** [comment]
LGTM.
