### ISSUE TITLE
gitup -V : invalid argument

### ISSUE THREAD

**Issue by nunotexbsd** [johnmehr/gitup#29]
Hello,

I remember that -V worked ok on 0.87 but not on 0.88:

gitup -V

gitup: 
Cannot find a matching section in the command line arguments.  These are the configured sections:
	 * ports
	 * quarterly
	 * release
	 * stable
	 * current
: Invalid argument

Thanks,

Nuno Texeira

**Comment by johnmehr** [comment]
Thank you for finding this!
