### ISSUE TITLE
gitup.conf : ignore section for revision controlled files?

### ISSUE THREAD

**Issue by nunotexbsd** [johnmehr/gitup#31]
Hello,

I'm using gitup to get 12.2 src and I noticed that gitup.conf have:
"release" : {
...
"ignore"     : [
                        "/usr/src/sys/amd64/conf",
                        ...
What happens if this files are changed by upstream since they are under revision control?

In ports section it make sense to use it:
"ports" : {
...
"ignore"     : [
                        "/usr/ports/distfiles",
                        "/usr/ports/packages",
because distfiles and packages aren't under revision control.

Thanks,

Nuno Teixeira

**Comment by johnmehr** [comment]
The "ignores" directories are only ignored when gitup is deleting files and upstream changes to files in /usr/src/sys/amd64/conf should be pulled down.  For example, if you "mv GENERIC MY_KERNEL", edit DEFAULTS by adding a couple of carriage returns and then run gitup, it will detect the changes, go into "repair mode" and fetch the missing/modified files while ignoring MY_KERNEL.

**Comment by nunotexbsd** [comment]
ok. Thanks!
