### ISSUE TITLE
unclear error when CONFIG_FILE_PATH points to a directory

### ISSUE THREAD

**Issue by emaste** [johnmehr/gitup#37]
I accidentally built with CONFIG_FILE_PATH pointing to a directory, not the file itself, and the error for this (admittedly unusual) case is unclear:

```
$ ./gitup stable
gitup: load_configuration: cannot stat file /usr/home/emaste/src/gitup: No error: 0: No error: 0
```

**Comment by johnmehr** [comment]
I just pushed out a fix for the duplicate "No error: 0" but it doesn't look like libucl will let me adjust the error code of 0 -- there doesn't appear to be a function that lets me manually set that value and trying to set `parser->err_code = value` throws an error.

**Comment by johnmehr** [comment]
I think I've found a workaround that replaces "No error: 0" with "Input/output error".  Thank you!

**Comment by michael-o** [comment]
I am confused, why not use `stat(2)` with `S_ISREG()` macro?

**Comment by johnmehr** [comment]
I just added a `stat(2)` check.  How does it look now?

**Comment by emaste** [comment]
That's a nicer error for my original case:
```
gitup: load_configuration: cannot load /home/emaste/src/gitup: Is a directory
```

We can still trigger less-nice errors, albeit in cases less likely to be hit accidentally:
```
$ ./gitup -C /dev/null stable
load_configuration: cannot stat file /dev/null: No error: 0
```

**Comment by johnmehr** [comment]
I just added a nicer error message for character devices, fifos and whiteouts.  Did I miss any others?

**Comment by michael-o** [comment]
> 
> 
> I just added a nicer error message for character devices, fifos and whiteouts. Did I miss any others?

While the change seems to be nice, does not make sense to handle each negative case instead of handling one positive case? Simply says that the path isn't a regular file?

**Comment by johnmehr** [comment]
Good call (thank you!)  How does it look now?

**Comment by michael-o** [comment]
LGTM:
```
# /gitup -C /
gitup: load_configuration: cannot load /: Inappropriate file type or format
root@bsd1srv:~/gitup (main %=)
# /gitup -C /dev/ada
ada0    ada0p2  ada0p4  ada0p6  ada1    ada2
ada0p1  ada0p3  ada0p5  ada0p7  ada1p1  ada2p1
root@bsd1srv:~/gitup (main %=)
# /gitup -C /dev/ada2p1
gitup: load_configuration: cannot load /dev/ada2p1: Inappropriate file type or format
root@bsd1srv:~/gitup (main %=)
# /gitup -C /dev/std
stderr  stdin   stdout
root@bsd1srv:~/gitup (main %=)
# /gitup -C /dev/stdout
gitup: load_configuration: cannot load /dev/stdout: Inappropriate file type or format
```

@emaste WDYT?

**Comment by emaste** [comment]
Yes LGTM

**Comment by michael-o** [comment]
Please close this then.
