### ISSUE TITLE
FreeBSD port pkg-message warning

### ISSUE THREAD

**Issue by nunotexbsd** [johnmehr/gitup#42]
Hello!

pkg-message says:

"Currently this program is beta, so the usual caveats/warnings (don't
use it in a production environment, make sure you've got backups, dont
(yet) run as root) apply."

When can I delete this message?
What is current state of gitup? Beta?

Yesterday, I used gitup to fetch FreeBSD 12.2 src and it worked fast like a charm.
I compiled a port that needed src and everything is working fine.

Thanks,

Nuno Teixeira

**Comment by michael-o** [comment]
@nunotexbsd Even better, this must be part of base. @emaste You and me have invested quite some time into this tool. Do you see a chance to have this in base as a suitable replacement for svnlite? This would make the system complete and solve the chicken and egg problem.

**Comment by nunotexbsd** [comment]
yes! It would be so cool!

What could we do? Talk with who? To make it happen?

**Comment by johnmehr** [comment]
I think it's solid enough now that we can remove the beta warning.  Thank you!

**Comment by nunotexbsd** [comment]
:)
Thank you!

**Comment by emaste** [comment]
Let's discuss the idea of bringing into base on the freebsd-git mailing list.

One note is that the base system prefers that we adhere to style(9); the largest divergence is probably the >80 col lines in gitup.c. I passed gitup.c through clang-format to see what it would do, and put the result in https://reviews.freebsd.org/D28541 (also https://github.com/emaste/gitup/commit/85c37a6a2eabca9a3521a3e037990af9708fc2e9). In any case I think we should discuss it on the mailing list first.

It would be good to apply capsicum(4), but that's also something that can be discussed separately.

**Comment by emaste** [comment]
> on the freebsd-git mailing list

@michael-o or @johnmehr feel free to start a thread on that if you like, or I will get to it a little bit later on.

**Comment by nunotexbsd** [comment]
I've just subscribed freebsd-git and I'm following phabricator.

Thanks all!

**Comment by nunotexbsd** [comment]
Should I close this issue?

**Comment by nunotexbsd** [comment]
I will close it when https://reviews.freebsd.org/D28608 is ready to land :)

**Comment by nunotexbsd** [comment]
https://www.freshports.org/net/gitup/

Thank you!
