### ISSUE TITLE
.gituprevision has no newline at EOF

### ISSUE THREAD

**Issue by emaste** [johnmehr/gitup#45]
Unless other tooling is incompatible with a newline at EOF I think it's beneficial to have it, in case users do e.g. `cat .gituprevision`.

Currently looks like:
```
00000000  73 74 61 62 6c 65 2f 31  32 3a 36 61 39 37 61 32  |stable/12:6a97a2|
00000010  33 37 61                                          |37a|
```

Base system newvers.sh parses .gituprevision with something like `awk -F: '{print $2}'` and works fine with the newline.

**Comment by johnmehr** [comment]
Done!
