### ISSUE TITLE
Logical inconsistencies in gitup.conf

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#47]
I see two logical inconsistencies in gitup.conf:

* `repository` is supposed to denote a repo name, but infact it denotes a repository path of the entire repository URL. I think this property should be named `repository_path` or something else.
* `target` is actually a directory, but does not carry `_directory` while `work_directory` does. Maybe even `clone_directory` since gitup puts the clone into it.

The first seems wrong and the second inconsistent to me.

**Comment by johnmehr** [comment]
I just renamed 'target' to 'target_directory' and 'repository' to 'repository_path'.  Thank you!

**Comment by michael-o** [comment]
LGTM
