### ISSUE TITLE
gitup does not create intermediate directories

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#50]
I have configured the database directory to point to: `/var/osipovmi/db/gitup` and gitup says:
```
$ ./gitup -v 2 -C gitup.conf stable
# Configuration file: gitup.conf
gitup: main: cannot create /var/osipovmi/db/gitup: No such file or directory
```
` /var/osipovmi/db` does not exist. I think either it should be documented that gitup does not create intermediate directories or it should create it silently.

**Comment by johnmehr** [comment]
How does it look now?

**Comment by michael-o** [comment]
Works for me now!
