### ISSUE TITLE
Don't mirror agent from server in a request

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#53]
gitup copies the server's agent string from the v2 wire protocol and sends requests with that one. I believe this one is wrong. The [documentation says](https://git-scm.com/docs/protocol-v2#_agent):
> The agent strings are purely informative for statistics and debugging purposes, and MUST NOT be used to programmatically assume the presence or absence of particular features.

Since we aren't `git(1)` just like the `User-Agent` header I would expect to see the same value here as in the header.

**Comment by johnmehr** [comment]
The official git client sends the agent of the server in its requests (I found the syntax via packet traces).  Removing it doesn't appear to have any negative effects but I may have to put it back in if it causes problems in the future.  Thanks!

**Comment by michael-o** [comment]
If it causes problem then the backend isn't spec compliant.
Looking into the change...

**Comment by michael-o** [comment]
Works for me.
