### ISSUE TITLE
Location of setsocketopt

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#60]
I am by far not an expect, but I am confused why socket options are set here: https://github.com/johnmehr/gitup/blob/2547cfcaf9ddf20b4ebb9b6aac6b7b1c0fc7d56d/gitup.c#L853-L871 in `setup_ssl()` instead of in `connect_server()`. TLS is set up when the connection has already been established.

**Comment by johnmehr** [comment]
This was a bad copy/paste on my part.  How does it look now?

**Comment by michael-o** [comment]
LGTM.
