### ISSUE TITLE
FreeBSD 13.0 error: gitup: connect_server: socket failure: Address family not supported by protocol family

### ISSUE THREAD

**Issue by edinilsonjs** [johnmehr/gitup#65]
After migrate from FreeBSD 12.2 RELEASE to FreeBSD 13.0 RELEASE, gitup is raising the following error:
gitup: connect_server: socket failure: Address family not supported by protocol family

Any tip?

gitup -V
gitup version 0.91

gitup ports
# Host: git.freebsd.org
# Port: 443
# Repository Path: /ports.git
# Target Directory: /usr/ports
# Have: f6f44b6cfe29d62a254a2deac5b7271fae1797cf
gitup: connect_server: socket failure: Address family not supported by protocol family

**Comment by fiebrandt** [comment]
would you mind to share output of:

`getaddrinfo -f unspec git.freebsd.org`

I am currently suspecting that with 13.0-RELEASE the return order of getaddrinfo in your case differs from 12.

**Comment by gphoto6** [comment]
Hello, I have a similar problem on freebsd 13 , custom kernel without ipv6.
`getaddrinfo -f unspec git.freebsd.org`
   dgram inet6 udp 2402:3d00:fb5d::e6a:1 0
   stream inet6 tcp 2402:3d00:fb5d::e6a:1 0
   seqpacket inet6 sctp 2402:3d00:fb5d::e6a:1 0
   dgram inet udp 192.50.199.252 0
   stream inet tcp 192.50.199.252 0
   seqpacket inet sctp 192.50.199.252 0

**Comment by johnmehr** [comment]
> Hello, I have a similar problem on freebsd 13 , custom kernel without ipv6.
> `getaddrinfo -f unspec git.freebsd.org`
> dgram inet6 udp 2402:3d00:fb5d::e6a:1 0
> stream inet6 tcp 2402:3d00:fb5d::e6a:1 0
> seqpacket inet6 sctp 2402:3d00:fb5d::e6a:1 0
> dgram inet udp 192.50.199.252 0
> stream inet tcp 192.50.199.252 0
> seqpacket inet sctp 192.50.199.252 0

Is it still not working with the latest commit (or anything after @fiebrandt's patch commited at aa82c6bf6ac4f5838cc09ac2b6e0f8c23776ffaf)?

**Comment by fiebrandt** [comment]
> Hello, I have a similar problem on freebsd 13 , custom kernel without ipv6.
> `getaddrinfo -f unspec git.freebsd.org`
> dgram inet6 udp 2402:3d00:fb5d::e6a:1 0
> stream inet6 tcp 2402:3d00:fb5d::e6a:1 0
[...]

Thanks for your feedback! In case you see as above in the error message `gitup: connect_server: socket failure:` you most likely running older version. Please make sure you're running the lastest version direct from githup. If that is still not working, please run gitup with truss `truss ./gitup ports` and upload the output here.

**Comment by gphoto6** [comment]
> > Hello, I have a similar problem on freebsd 13 , custom kernel without ipv6.
> > `getaddrinfo -f unspec git.freebsd.org`
> > dgram inet6 udp 2402:3d00:fb5d::e6a:1 0
> > stream inet6 tcp 2402:3d00:fb5d::e6a:1 0
> > seqpacket inet6 sctp 2402:3d00:fb5d::e6a:1 0
> > dgram inet udp 192.50.199.252 0
> > stream inet tcp 192.50.199.252 0
> > seqpacket inet sctp 192.50.199.252 0
> 
> Is it still not working with the latest commit (or anything after @fiebrandt's patch commited at [aa82c6b](https://github.com/johnmehr/gitup/commit/aa82c6bf6ac4f5838cc09ac2b6e0f8c23776ffaf))?

My gitup is installed by "pkg", and the latest package update time is 4/23. I guess it is not updated to the latest version.

**Comment by gphoto6** [comment]
> > Hello, I have a similar problem on freebsd 13 , custom kernel without ipv6.
> > `getaddrinfo -f unspec git.freebsd.org`
> > dgram inet6 udp 2402:3d00:fb5d::e6a:1 0
> > stream inet6 tcp 2402:3d00:fb5d::e6a:1 0
> > [...]
> 
> Thanks for your feedback! In case you see as above in the error message `gitup: connect_server: socket failure:` you most likely running older version. Please make sure you're running the lastest version direct from githup. If that is still not working, please run gitup with truss `truss ./gitup ports` and upload the output here.

Here comes the output:

mmap(0x0,135168,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34362032128 (0x800230000)
mprotect(0x80022d000,4096,PROT_READ)             = 0 (0x0)
issetugid()                                      = 0 (0x0)
sigfastblock(0x1,0x80022f510)                    = 0 (0x0)
open("/etc/libmap.conf",O_RDONLY|O_CLOEXEC,010566710) = 3 (0x3)
fstat(3,{ mode=-rw-r--r-- ,inode=1098,size=47,blksize=4096 }) = 0 (0x0)
read(3,"# $FreeBSD$\nincludedir /usr/loc"...,47) = 47 (0x2f)
close(3)                                         = 0 (0x0)
open("/usr/local/etc/libmap.d",O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC,0165) ERR#2 'No such file or directory'
open("/var/run/ld-elf.so.hints",O_RDONLY|O_CLOEXEC,010012610) = 3 (0x3)
read(3,"Ehnt\^A\0\0\0\M^@\0\0\0k\0\0\0\0"...,128) = 128 (0x80)
fstat(3,{ mode=-r--r--r-- ,inode=10014,size=235,blksize=4096 }) = 0 (0x0)
pread(3,"/lib:/usr/lib:/usr/lib/compat:/u"...,107,0x80) = 107 (0x6b)
close(3)                                         = 0 (0x0)
open("/lib/libssl.so.111",O_RDONLY|O_CLOEXEC|O_VERIFY,024047400) ERR#2 'No such file or directory'
open("/usr/lib/libssl.so.111",O_RDONLY|O_CLOEXEC|O_VERIFY,024047400) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=199818,size=609704,blksize=131072 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,622592,PROT_NONE,MAP_GUARD,-1,0x0)      = 34362171392 (0x800252000)
mmap(0x800252000,233472,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34362171392 (0x800252000)
mmap(0x80028b000,327680,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x38000) = 34362404864 (0x80028b000)
mmap(0x8002db000,36864,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x87000) = 34362732544 (0x8002db000)
mmap(0x8002e4000,24576,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x8f000) = 34362769408 (0x8002e4000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/lib/libz.so.6",O_RDONLY|O_CLOEXEC|O_VERIFY,023055000) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=196615,size=103840,blksize=103936 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,114688,PROT_NONE,MAP_GUARD,-1,0x0)      = 34362793984 (0x8002ea000)
mmap(0x8002ea000,36864,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34362793984 (0x8002ea000)
mmap(0x8002f3000,69632,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x8000) = 34362830848 (0x8002f3000)
mmap(0x800304000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x18000) = 34362900480 (0x800304000)
mmap(0x800305000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x18000) = 34362904576 (0x800305000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/lib/libcrypto.so.111",O_RDONLY|O_CLOEXEC|O_VERIFY,014232266000) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=199319,size=3074752,blksize=131072 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,3100672,PROT_NONE,MAP_GUARD,-1,0x0)     = 34362908672 (0x800306000)
mmap(0x800306000,1142784,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34362908672 (0x800306000)
mmap(0x80041e000,1736704,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x117000) = 34364055552 (0x80041e000)
mmap(0x8005c6000,176128,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x2be000) = 34365792256 (0x8005c6000)
mmap(0x8005f1000,28672,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x2e8000) = 34365968384 (0x8005f1000)
mmap(0x8005f8000,12288,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON,-1,0x0) = 34365997056 (0x8005f8000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/lib/libprivateucl.so.1",O_RDONLY|O_CLOEXEC|O_VERIFY,00) ERR#2 'No such file or directory'
open("/usr/lib/libprivateucl.so.1",O_RDONLY|O_CLOEXEC|O_VERIFY,00) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=196245,size=136792,blksize=131072 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,147456,PROT_NONE,MAP_GUARD,-1,0x0)      = 34366009344 (0x8005fb000)
mmap(0x8005fb000,45056,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34366009344 (0x8005fb000)
mmap(0x800606000,94208,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0xa000) = 34366054400 (0x800606000)
mmap(0x80061d000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x20000) = 34366148608 (0x80061d000)
mmap(0x80061e000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x20000) = 34366152704 (0x80061e000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/lib/libc.so.7",O_RDONLY|O_CLOEXEC|O_VERIFY,020443000) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=193162,size=1981864,blksize=131072 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,4263936,PROT_NONE,MAP_GUARD,-1,0x0)     = 34366156800 (0x80061f000)
mmap(0x80061f000,540672,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34366156800 (0x80061f000)
mmap(0x8006a3000,1384448,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x83000) = 34366697472 (0x8006a3000)
mmap(0x8007f5000,40960,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x1d4000) = 34368081920 (0x8007f5000)
mmap(0x8007ff000,28672,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x1dd000) = 34368122880 (0x8007ff000)
mmap(0x800806000,2269184,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON,-1,0x0) = 34368151552 (0x800806000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/lib/libthr.so.3",O_RDONLY|O_CLOEXEC|O_VERIFY,012320443000) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=195828,size=125952,blksize=125952 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,184320,PROT_NONE,MAP_GUARD,-1,0x0)      = 34370420736 (0x800a30000)
mmap(0x800a30000,53248,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34370420736 (0x800a30000)
mmap(0x800a3d000,73728,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0xc000) = 34370473984 (0x800a3d000)
mmap(0x800a4f000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x1d000) = 34370547712 (0x800a4f000)
mmap(0x800a50000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x1d000) = 34370551808 (0x800a50000)
mmap(0x800a52000,45056,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_ANON,-1,0x0) = 34370560000 (0x800a52000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/lib/libm.so.5",O_RDONLY|O_CLOEXEC|O_VERIFY,012320443000) = 3 (0x3)
fstat(3,{ mode=-r--r--r-- ,inode=194582,size=214192,blksize=131072 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,3,0x0) = 34362167296 (0x800251000)
mmap(0x0,225280,PROT_NONE,MAP_GUARD,-1,0x0)      = 34370605056 (0x800a5d000)
mmap(0x800a5d000,73728,PROT_READ,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x0) = 34370605056 (0x800a5d000)
mmap(0x800a6f000,143360,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,3,0x11000) = 34370678784 (0x800a6f000)
mmap(0x800a92000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x33000) = 34370822144 (0x800a92000)
mmap(0x800a93000,4096,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,3,0x33000) = 34370826240 (0x800a93000)
munmap(0x800251000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
mprotect(0x8002db000,32768,PROT_READ)            = 0 (0x0)
mprotect(0x800304000,4096,PROT_READ)             = 0 (0x0)
munmap(0x80023c000,86016)                        = 0 (0x0)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34370830336 (0x800a94000)
mprotect(0x8005c6000,172032,PROT_READ)           = 0 (0x0)
mprotect(0x80061d000,4096,PROT_READ)             = 0 (0x0)
mprotect(0x8007f5000,40960,PROT_READ)            = 0 (0x0)
mprotect(0x800a4f000,4096,PROT_READ)             = 0 (0x0)
mprotect(0x800a92000,4096,PROT_READ)             = 0 (0x0)
mprotect(0x8007f5000,40960,PROT_READ|PROT_WRITE) = 0 (0x0)
mprotect(0x8007f5000,40960,PROT_READ)            = 0 (0x0)
readlink("/etc/malloc.conf",0x7fffffffd680,1024) ERR#2 'No such file or directory'
issetugid()                                      = 0 (0x0)
__sysctl("vm.overcommit",2,0x7fffffffbc14,0x7fffffffbc08,0x0,0) = 0 (0x0)
mmap(0x0,2097152,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(21),-1,0x0) = 34372321280 (0x800c00000)
mmap(0x0,2097152,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(12),-1,0x0) = 34374418432 (0x800e00000)
mmap(0x0,4194304,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_ALIGNED(21),-1,0x0) = 34376515584 (0x801000000)
__sysctl("kern.usrstack",2,0x800a513c8,0x7fffffffdaf8,0x0,0) = 0 (0x0)
getrlimit(RLIMIT_STACK,{ cur=536870912,max=536870912 }) = 0 (0x0)
thr_self(0x800e12000)                            = 0 (0x0)
mmap(0x7fffdfffe000,4096,PROT_NONE,MAP_ANON,-1,0x0) = 140736951476224 (0x7fffdfffe000)
rtprio_thread(RTP_LOOKUP,100572,0x7fffffffdab8)  = 0 (0x0)
sigaction(SIGTHR,{ 0x800a494d0 SA_SIGINFO ss_t },0x0) = 0 (0x0)
sigprocmask(SIG_UNBLOCK,{ },0x0)                 = 0 (0x0)
_umtx_op(0x7fffffffdab0,UMTX_OP_WAKE,0x1,0x0,0x0) = 0 (0x0)
mprotect(0x0,0,PROT_NONE)                        = 0 (0x0)
getpid()                                         = 2520 (0x9d8)
getpid()                                         = 2520 (0x9d8)
sigprocmask(SIG_BLOCK,{ SIGHUP|SIGINT|SIGQUIT|SIGILL|SIGTRAP|SIGABRT|SIGEMT|SIGFPE|SIGKILL|SIGBUS|SIGSEGV|SIGSYS|SIGPIPE|SIGALRM|SIGTERM|SIGURG|SIGSTOP|SIGTSTP|SIGCONT|SIGCHLD|SIGTTIN|SIGTTOU|SIGIO|SIGXCPU|SIGXFSZ|SIGVTALRM|SIGPROF|SIGWINCH|SIGINFO|SIGUSR1|SIGUSR2 },{ }) = 0 (0x0)
sigfastblock(0x3,0x0)                            = 0 (0x0)
sigprocmask(SIG_SETMASK,{ },0x0)                 = 0 (0x0)
sigfastblock(0x1,0x800e12038)                    = 0 (0x0)
getcontext(0x7fffffffd5a0)                       = 0 (0x0)
sysarch(AMD64_GET_XFPUSTATE,0x7fffffffd568)      = 0 (0x0)
mprotect(0x20f000,4096,PROT_READ)                = 0 (0x0)
fstatat(AT_FDCWD,"/usr/local/etc/gitup.conf",{ mode=-rw-r--r-- ,inode=33121,size=1720,blksize=4096 },0x0) = 0 (0x0)
__getcwd("/etc",1024)                            = 0 (0x0)
__realpathat(AT_FDCWD,"/usr/local/etc/gitup.conf","/usr/local/etc/gitup.conf",1024,0) = 0 (0x0)
fstatat(AT_FDCWD,"/usr/local/etc/gitup.conf",{ mode=-rw-r--r-- ,inode=33121,size=1720,blksize=4096 },0x0) = 0 (0x0)
openat(AT_FDCWD,"/usr/local/etc/gitup.conf",O_RDONLY,00) = 3 (0x3)
mmap(0x0,1720,PROT_READ,MAP_SHARED,3,0x0)        = 34362081280 (0x80023c000)
close(3)                                         = 0 (0x0)
munmap(0x80023c000,1720)                         = 0 (0x0)
mkdir("/var/db/gitup",0755)                      ERR#17 'File exists'
fstatat(AT_FDCWD,"/var",{ mode=drwxr-xr-x ,inode=257,size=24,blksize=4096 },0x0) = 0 (0x0)
fstatat(AT_FDCWD,"/var/db",{ mode=drwxr-xr-x ,inode=291,size=19,blksize=4096 },0x0) = 0 (0x0)
mkdir("/var/db/gitup",0755)                      ERR#17 'File exists'
fstatat(AT_FDCWD,"/usr/ports",{ mode=drwxr-xr-x ,inode=34,size=2,blksize=4096 },0x0) = 0 (0x0)
fstatat(AT_FDCWD,"/var/db/gitup/ports",0x7fffffffb960,0x0) ERR#2 'No such file or directory'
fstatat(AT_FDCWD,"(null)",0x7fffffffb960,0x0)    ERR#14 'Bad address'
fstatat(AT_FDCWD,"/usr/ports",{ mode=drwxr-xr-x ,inode=34,size=2,blksize=4096 },0x0) = 0 (0x0)
open("/usr/ports",O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC,037777703360) = 3 (0x3)
fcntl(3,F_ISUNIONSTACK,0x0)                      = 0 (0x0)
getdirentries(3,""\0\0\0\0\0\0\0\^A\0\0\0\0\0\0\0"...,4096,{ 0x0 }) = 64 (0x40)
getdirentries(3,0x800e33000,4096,{ 0x2 })        = 0 (0x0)
close(3)                                         = 0 (0x0)
 # Host: git.freebsd.org
write(2,"# Host: git.freebsd.org\n",24)          = 24 (0x18)
 # Port: 443
write(2,"# Port: 443\n",12)                      = 12 (0xc)
 # Repository Path: /ports.git
write(2,"# Repository Path: /ports.git\n",30)    = 30 (0x1e)
 # Target Directory: /usr/ports
write(2,"# Target Directory: /usr/ports\n",31)   = 31 (0x1f)
fstatat(AT_FDCWD,"/etc/nsswitch.conf",{ mode=-rw-r--r-- ,inode=1152,size=272,blksize=4096 },0x0) = 0 (0x0)
open("/etc/nsswitch.conf",O_RDONLY|O_CLOEXEC,0666) = 3 (0x3)
fstat(3,{ mode=-rw-r--r-- ,inode=1152,size=272,blksize=4096 }) = 0 (0x0)
read(3,"#\n# nsswitch.conf(5) - name ser"...,4096) = 272 (0x110)
read(3,0x800e33000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
open("/etc/hosts",O_RDONLY|O_CLOEXEC,0666)       = 3 (0x3)
fstat(3,{ mode=-rw-r--r-- ,inode=1074,size=1031,blksize=4096 }) = 0 (0x0)
read(3,"# $FreeBSD$\n#\n# Host Database"...,4096) = 1031 (0x407)
read(3,0x800e33000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
getpid()                                         = 2520 (0x9d8)
issetugid()                                      = 0 (0x0)
open("/etc/resolv.conf",O_RDONLY|O_CLOEXEC,0666) = 3 (0x3)
fstat(3,{ mode=-rw-r--r-- ,inode=11616,size=19,blksize=4096 }) = 0 (0x0)
fstat(3,{ mode=-rw-r--r-- ,inode=11616,size=19,blksize=4096 }) = 0 (0x0)
read(3,"nameserver 8.8.8.8\n",4096)              = 19 (0x13)
read(3,0x800e33000,4096)                         = 0 (0x0)
close(3)                                         = 0 (0x0)
__sysctl("kern.hostname",2,0x7fffffff78c0,0x7fffffff75d8,0x0,0) = 0 (0x0)
issetugid()                                      = 0 (0x0)
socket(PF_INET,SOCK_DGRAM|SOCK_CLOEXEC,0)        = 3 (0x3)
connect(3,{ AF_INET 8.8.8.8:53 },16)             = 0 (0x0)
sendto(3,"\M-W?\^A\0\0\^A\0\0\0\0\0\0\^Cgi"...,33,0,NULL,0) = 33 (0x21)
poll({ 3/POLLRDNORM },1,5000)                    = 1 (0x1)
recvfrom(3,"\M-W?\M^A\M^@\0\^A\0\^B\0\0\0\0"...,65536,0,{ AF_INET 8.8.8.8:53 },0x7fffffff71c8) = 74 (0x4a)
close(3)                                         = 0 (0x0)
socket(PF_INET,SOCK_DGRAM|SOCK_CLOEXEC,0)        = 3 (0x3)
connect(3,{ AF_INET 8.8.8.8:53 },16)             = 0 (0x0)
sendto(3,"\M^L=\^A\0\0\^A\0\0\0\0\0\0\^Cgi"...,33,0,NULL,0) = 33 (0x21)
poll({ 3/POLLRDNORM },1,5000)                    = 1 (0x1)
recvfrom(3,"\M^L=\M^A\M^@\0\^A\0\^B\0\0\0\0"...,65536,0,{ AF_INET 8.8.8.8:53 },0x7fffffff71c8) = 86 (0x56)
close(3)                                         = 0 (0x0)
__sysctl("net.28.41.38",4,0x0,0x7fffffff8750,0x0,0) ERR#2 'No such file or directory'
socket(PF_INET6,SOCK_STREAM,IPPROTO_TCP)         ERR#47 'Address family not supported by protocol family'
gitup: write(2,"gitup: ",7)                              = 7 (0x7)
connect_server: socket failurewrite(2,"connect_server: socket failure",30)      = 30 (0x1e)
: write(2,": ",2)                                        = 2 (0x2)
fstatat(AT_FDCWD,"/usr/share/nls/C/libc.cat",0x7fffffff8530,0x0) ERR#2 'No such file or directory'
fstatat(AT_FDCWD,"/usr/share/nls/libc/C",0x7fffffff8530,0x0) ERR#2 'No such file or directory'
fstatat(AT_FDCWD,"/usr/local/share/nls/C/libc.cat",0x7fffffff8530,0x0) ERR#2 'No such file or directory'
fstatat(AT_FDCWD,"/usr/local/share/nls/libc/C",0x7fffffff8530,0x0) ERR#2 'No such file or directory'
Address family not supported by protocol family
write(2,"Address family not supported by "...,48) = 48 (0x30)
exit(0x1)
process exit, rval = 1

**Comment by gphoto6** [comment]
After upgrading to version 0.92, it seems to solve this problem!!
Thanks very very much.

This time I download the gitup source from github and compile by myself.
However, most of my servers are using 'pkg', so I need to wait for 'pkg' release the new gitup version.
