### ISSUE TITLE
Two issues in `send_command`

### ISSUE THREAD

**Issue by blacklion** [johnmehr/gitup#7]
https://github.com/johnmehr/gitup/blob/6e3578902887b5d4d4dd1d1a9d669689241299ab/gitup.c#L950

1. `BUFFER_UNIT_SMALL + want_size` bytes is allocated, but up to `BUFFER_UNIT_LARGE` could be filled up.

1. `Host: github.com` is hardcoded into request.

**Comment by johnmehr** [comment]
Thank you for finding these!  I just pushed out an update that corrects the bugs.

**Comment by johnmehr** [comment]
Sorry about that!  Those were leftovers from some code I decided to remove for now.  One of the things I really want gitup to be able to do is repair a local tree in case files are deleted so that after every update, the local tree is always in a usable state.
