### ISSUE TITLE
Make repair scriptable

### ISSUE THREAD

**Issue by michael-o** [johnmehr/gitup#78]
I'd like to automate gitup, but this is a problem:

https://github.com/johnmehr/gitup/blob/aad38a82b254e461bd6337ce72bfe7f2bf6b4d13/gitup.c#L4131-L4134

Basically, the return code is still zero althrough I need to rerun gitup. From a script (`periodic(8)`) I cannot detect that w/o grepping through the output which I don't want to.

My request is to either return another, well defined, exit code or make it configurable to return non-zero for that.

**Comment by johnmehr** [comment]
I just added code to return a value of 2 if a repair occurs.  How does it work for you now?

**Comment by michael-o** [comment]
> I just added code to return a value of 2 if a repair occurs. How does it work for you now?

Yes, this works for me, but should also be reflected in the manpage.

**Comment by johnmehr** [comment]
Gah!  Sorry about that!

**Comment by michael-o** [comment]
Looks good to me.
