### ISSUE TITLE
Why is permanent information saved in `/var/tmp`?

### ISSUE THREAD

**Issue by blacklion** [johnmehr/gitup#8]
https://github.com/johnmehr/gitup/blob/6e3578902887b5d4d4dd1d1a9d669689241299ab/gitup.conf#L9

Maybe, `/var/db/gitup` is better suited for such data, as with `portsnap` and `freebsd-update`? `/var/tmp` could be cleaned up at any time.

**Comment by johnmehr** [comment]
Hello,

This behavior is a holdover from the svnup days -- because svnup was only a port, I was instructed by one of the FreeBSD committers to store these files in /var/tmp.  If it's ok for gitup to use /var/db, I can make the switch.

**Comment by blacklion** [comment]
BTW, why don't you use `libucl` for config?

**Comment by johnmehr** [comment]
I've never heard of libucl.  I'll check it out!

**Comment by johnmehr** [comment]
I just converted the configuration code to use libucl and set /var/db/gitup as the work directory.

Thank you!
