### ISSUE TITLE
/usr/src is not updated when empty

### ISSUE THREAD

**Issue by xmacan** [johnmehr/gitup#85]
gitup: build_repair_command: There are too many files to repair -- please re-clone the repository: Argument list too long

It would be great if gitup could download resources even if the folder is empty. There would be no need for another tool or downloading from the web.

**Comment by johnmehr** [comment]
I just committed a patch that doesn't attempt a repair when the local repository folder exists but is empty.  How does it work for you?

**Comment by xmacan** [comment]
It works great! Thank you!

[root@somewehre /usr/src]# rm -rf *
[root@somewehre /usr/src]# rm .*
rm: "." and ".." may not be removed
[root@somewhere /usr/src]# ls -al
total 8
drwxr-xr-x   2 root  wheel  1024 Sep 20 08:07 .
drwxr-xr-x  16 root  wheel   512 Oct 15  2021 ..

[root@somewhere /usr/src]# gitup release
# Host: git.freebsd.org
# Port: 443
# Repository Path: /src.git
# Target Directory: /usr/src
# Want: d106002967eff712894ab8b5337bbbff106ce5e0
# Branch: releng/11.4
....
#
# Done.
