### ISSUE TITLE
error - : Invalid argument

### ISSUE THREAD

**Issue by xmacan** [johnmehr/gitup#87]
Version 0.97 and 0.98, 12.3-RELEASE-p6 FreeBSD 12.3-RELEASE-p6 GENERIC  amd64

gitup release (12.3) ends:
00799399617194d8919c03460eeeb49aa5e7bb930047 refs/tags/vendor/zstd/1.4.1 peeled:fa94c7381af469a06d8f9077162c2cc5dee581cb
0079e103cc7d192afc1de4ebc29e6e467651c6436112 refs/tags/vendor/zstd/1.4.2 peeled:90f4bdbe917eaf678feca2b0ff9647b5ae8bbb9d
007941746347b22e30608746cf036cb3b36bc24d2ab3 refs/tags/vendor/zstd/1.4.4 peeled:ea68403922c3b53b00fc999fcb3eaef1feb50177
0079f57d3351ea7669d274e6763623c24bc2f14e0bcb refs/tags/vendor/zstd/1.4.5 peeled:bc64b5ce191d48b503e4fad8c0cefb774a2fa969
0079097cf2d98ee47f2e18a32db1453a5fd9a0583570 refs/tags/vendor/zstd/1.4.8 peeled:f6ae97673c28bdb9ae795bd235ab6f26f2536a2d
0000

: Invalid argument

**Comment by johnmehr** [comment]
I'm not having any luck reproducing the error.  Could you please let me know what have/want values are being used and could you include a copy of your gitup.conf?  Thanks!

**Comment by xmacan** [comment]
12.3-RELEASE-p6 FreeBSD 12.3-RELEASE-p6 GENERIC  amd64
# $FreeBSD$
#
# Default configuration options for gitup.conf.
{
	"defaults" : {
		"host"           : "git.freebsd.org",
		"port"           : 443,
#		"proxy_host"     : "",
#		"proxy_port"     : 0,
#		"proxy_username" : "",
#		"proxy_password" : "",
#		"source_address" : "",
		"low_memory"     : false,
		"display_depth"  : 0,
		"verbosity"      : 1,
		"work_directory" : "/var/db/gitup",
	},

	"ports" : {
		"repository_path"  : "/ports.git",
		"branch"           : "main",
		"target_directory" : "/usr/ports",
		"ignores"          : [],
	},

	"quarterly" : {
		"repository_path"  : "/ports.git",
		"branch"           : "quarterly",
		"target_directory" : "/usr/ports",
		"ignores"          : [],
	},

	"release" : {
		"repository_path"  : "/src.git",
		"branch"           : "releng/12.3",
		"target_directory" : "/usr/src",
		"ignores"          : [
			"sys/[^\/]+/conf",
		],
	},

	"stable" : {
		"repository_path"  : "/src.git",
		"branch"           : "stable/12",
		"target_directory" : "/usr/src",
		"ignores"          : [
			"sys/[^\/]+/conf",
		],
	},

	"current" : {
		"repository_path"  : "/src.git",
		"branch"           : "main",
		"target_directory" : "/usr/src",
		"ignores"          : [
			"sys/[^\/]+/conf",
		],
	}
}
[root@arpwatch /home/pm]# gitup release
# Scanning local repository...
# Host: git.freebsd.org
# Port: 443
# Repository Path: /src.git
# Target Directory: /usr/src
# Want: 04043434d294cef8e39275444b46e9f36e2eb0e9
# Branch: releng/12.3
gitup: process_command: read failure:
0050da69782bf06645f38852a8b23afc965fc30d0e08 HEAD symref-target:refs/heads/main
003dda69782bf06645f38852a8b23afc965fc30d0e08 refs/heads/main
00415e0e9b99dc3fc0ecd49d929db0d57c784b66f481 refs/heads/releng/1
00440099f6f89a1325dc504096aecbdcbddad498310e refs/heads/releng/10.0
0044a9b4be204689211fddaab97ddd6df73b8f44d222 refs/heads/releng/10.1
00442a3488342441b3296995c8a9eca705a468d0eff0 refs/heads/releng/10.2
...
...
0079f57d3351ea7669d274e6763623c24bc2f14e0bcb refs/tags/vendor/zstd/1.4.5 peeled:bc64b5ce191d48b503e4fad8c0cefb774a2fa969
0079097cf2d98ee47f2e18a32db1453a5fd9a0583570 refs/tags/vendor/zstd/1.4.8 peeled:f6ae97673c28bdb9ae795bd235ab6f26f2536a2d
0000

: Invalid argument

Suspecting my FreeBSD because I'm using gitup on dozens of FreeBSD and this issue is only here. Bud I don't know what is wrong.

**Comment by xmacan** [comment]
Ups.... I found the reason - there is packet deep inspection on firewall and BSD hasn't correct certificate. I tried disable the inspection and it works without problem. So it isn't gitup issue.
Thank you

**Comment by johnmehr** [comment]
No worries!  I actually wouldn't mind seeing the header output when you have inspection enabled -- gitup gets unhappy when the header doesn't begin with "HTTP/1." and I could relax this check to be ok it if "HTTP/1." appears anywhere in the header.

**Comment by xmacan** [comment]
0079097cf2d98ee47f2e18a32db1453a5fd9a0583570 refs/tags/vendor/zstd/1.4.8 peeled:f6ae97673c28bdb9ae795bd235ab6f26f2536a2d
0000

: Invalid argument


==========

==========
HTTP/1.1 200 OK
Server: nginx/1.22.1
Date: Mon, 19 Dec 2022 09:09:06 GMT
Content-Type: application/x-git-upload-pack-result
Transfer-Encoding: chunked
Connection: keep-alive
Expires: Fri, 01 Jan 1980 00:00:00 GMT
Pragma: no-cache
Cache-Control: no-cache, max-age=0, must-revalidate

1f53
00508f7859e800d998e5518b4f0d6c9545106dc96f68 HEAD symref-target:refs/heads/main
003d8f7859e800d998e5518b4f0d6c9545106dc96f68 refs/heads/main
00415e0e9b99dc3fc0ecd49d929db0d57c784b66f481 refs/heads/releng/1

**Comment by johnmehr** [comment]
Darn.  I was hoping to see some clues but the output looks normal.  If it's ok with you, I'm going to close this issue.  Thanks!
