### ISSUE TITLE
Feature Proposal: automatically chasing latest quarterly branch of ports repository

### ISSUE THREAD

**Issue by yasuhirokimura** [johnmehr/gitup#9]
Since I'm not familiar with the internal of Git, I'm not sure if it is really possible to implement. But I'd like to propose a new feature of gitup anyway.

If someone want to use ports tree there are two choices. That is, head (main, master) or quarterly branch. I myself always use head and build and install packages by myself. But if I guess how an average user uses ports/packages, probably he uses official packages in most cases and uses ports only when necessary (e.g, He wants to build package with non default options settings). And for such user quarterly branch is preferable one since default selection of official packages are quarterly.

But for user who isn't familiar with ports tree management it is a bit troublesome to use quarterly branch. As its name explains new quarterly branch is created every 3 months. So user need to switch to new one every time it is created. From the viewpoint of gitup user have to edit gitup.conf so gitup pulls the latest quarterly branch. But maybe average user doesn't pay much attention when new quarterly branch is created. And as a result he may continue to use old one that isn't updated anymore.

So I'd like to propose a new feature that automatically chase latest quarterly branch of ports repository. As I wrote above I'm not sure if it is possible to implement. But please consider it and implement it if it is possible.

Best Regards.

**Comment by johnmehr** [comment]
I think this is possible.  I just ran a test where I cloned 2020Q3 and then pulled 2020Q4 and only eight files had problems so there's probably an obscure bug I need to track down.  Once I get that sorted out, it shouldn't be too difficult to automatically identify the most recent quarterly branch and pull it down.

For the gitup.conf section, what name do you think makes the most sense to use?  Maybe 'quarterly'?  'ports-quarterly'?  Something else?

Thank you!

**Comment by johnmehr** [comment]
It looks like the discrepancy with the eight files was due to an update to the 2020Q4 branch that took place while I was testing it -- I just ran another test making sure that the repository I fetched with git had the same commit as the repository I fetched with gitup and it was a 100% match.

I'll start writing the code to find the most recent quarterly branch and I should be able to push it out by Saturday.

Thank you!

**Comment by yasuhirokimura** [comment]
Thank you for considering my proposal immediately. I am very happy to hear that my proposal is implementable.

> For the gitup.conf section, what name do you think makes the most sense to use? Maybe 'quarterly'? 'ports-quarterly'? Something else?

Only ports repository has a quarterly branch, so I prefer simple "quarterly".

**Comment by johnmehr** [comment]
Done!  Thank you!
