### ISSUE TITLE
Scanning before cloning

### ISSUE THREAD

**Issue by grahamperrin** [johnmehr/gitup#92]
```text
root@fuji:~ # time gitup -c ports
# Scanning local repository...
^C0.518u 0.189s 0:12.26 5.6%    67+165k 1157+0io 8pf+0w
You have new mail.
root@fuji:~ # 
```

If `-c` is to _force_ a clone, then what's the purpose of a preceding scan?

I imagined forced removal, not a scan. 

(Did I `^C` abort too soon? Am I missing something?)

**Comment by grahamperrin** [comment]
With a _manually_ forced removal: 

```text
root@fuji:~ # time rm -r /usr/ports/*
0.655u 17.045s 4:12.76 6.9%     10+169k 21175+0io 0pf+0w
root@fuji:~ # time gitup -c ports
# Scanning local repository...
# Host: git.freebsd.org
# Port: 443
# Repository Path: /ports.git
# Target Directory: /usr/ports
# Have: 3709a507f75c701e4da6844c28d69dc5047a87d3
# Want: 674dc7b4910df11ba2ec097dca68d3cbc883442e
# Branch: main
…
```

**Comment by johnmehr** [comment]
Sorry for dropping the ball on this one.  I just added an update that should correct the behavior you're seeing.  I'm a little leery about forced removals so gitup now aborts if a clone is attempted on a directory with files present.

**Comment by johnmehr** [comment]
If there are any problems with this new fix, please let me know. Thanks!
