### ISSUE TITLE
Option -p for the path to an alternative local repo

### ISSUE THREAD

**Issue by grahamperrin** [johnmehr/gitup#98]
Comparable to git(1) option [-C](https://git-scm.com/docs/git#Documentation/git.txt--Cltpathgt), which I habitually use with Git.

gitup(1) [OPTIONS](https://man.freebsd.org/cgi/man.cgi?query=gitup&sektion=1&manpath=freebsd-ports#OPTIONS) already have an alternative use for `-C`, and `-t` is for tag, so, I guess: 

```text
       -p        Path to an alternative local repository (override the
                 `target_directory` that is specified in gitup.conf(5)).
```

Enhancement. Thanks!

**Comment by johnmehr** [comment]
How does this work for you?

**Comment by johnmehr** [comment]
If there are any problems with this new feature, please let me know.  Thanks!
